config/routes.rb
Rails.application.routes.draw do
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # delete '/products/:id', to: 'products#destroy'
  # patch '/products/:id', to: 'products#update'
  # post '/products', to: 'products#create'
  # get '/products/new', to: 'products#new', as: :new_product
  # get '/products', to: 'products#index'
  # get '/products/:id', to: 'products#show', as: :product
  # get '/products/:id/edit', to: 'products#edit', as: :edit_product

  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create], path: '/register', path_names: { new: '/'}
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/'}
  end

  resources :favorites, only: [:index, :create, :destroy], param: :product_id
  resources :users, only: :show, path: '/user', param: :username
  resources :categories, except: :show
  resources :products, path: '/'
end

app/models/product.rb
class Product < ApplicationRecord
  # PG search
  include PgSearch::Model

  # Favorites
  include Favoritable

  pg_search_scope :search_full_text, against: {
    title: 'A',
    description: 'B',
  }

  # Variables
  ORDER_BY = {
    newest: "created_at DESC",
    expensive: "price DESC",
    cheapest: "price ASC"
  }

  # Active storage
  has_one_attached :photo

  # Validates
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

  # Associations
  belongs_to :category
  belongs_to :user, default: -> { Current.user }

  def owner?
    user_id == Current.user&.id
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :protect_pages, only: [:index, :show]

  def index
    @categories = Category.order(name: :asc).load_async

    @pagy, @products = pagy_countless(FindProducts.new.call(product_params_index).load_async, items: 12)
  end

  def show
    set_product
  end

  def new
    @product = Product.new
  end

  def edit
    authorize! set_product
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: t('.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize! set_product

    if set_product.update(product_params)
      redirect_to products_path, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! set_product

    set_product.destroy

    redirect_to products_path, alert: t('.destroyed'), status: :see_other
  end

  private

    def set_product
      @product ||= Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :category_id, :description, :price, :photo)
    end

    def product_params_index
      params.permit(:category_id, :min_price, :max_price, :query_text, :order_by, :page, :user_id, :favorites)
    end
end

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id), class: "category mr-2 underline" do %>
  <%= category.name %>
<% end %>

app/views/products/_favorite.html.erb
<div id="favorite">
  <% if product.favorite %>
    <%= link_to "💔", favorite_path(product.id), data: { turbo_method: :delete }, class: "inline-block px-6 py-2.5 bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl text-white font-medium text-xs leading-tight uppercase rounded shadow-md active:shadow-lg transition duration-150 ease-in-out" %>
  <% else %>
    <%= link_to "💓", favorites_path(product_id: product.id), data: { turbo_method: :post }, class: "inline-block px-6 py-2.5 bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl text-white font-medium text-xs leading-tight uppercase rounded shadow-md active:shadow-lg transition duration-150 ease-in-out" %>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with model: product do |f| %>
  <%= render "shared/form_errors", form: f %>

  <div class="flex flex-col mb-2">
    <%= f.label :title %>
    <%= f.text_field :title, class: "w-full md:w-1/2 rounded", placeholder: "Nintendo Switch..." %>
  </div>

  <div class="flex flex-col mb-2 w-full md:w-1/2">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all.order(name: :asc), :id, :name %>
  </div>

  <div class="flex flex-col mb-2">
    <%= f.label :description %>
    <%= f.text_area :description, class: "w-full md:w-1/2 rounded", placeholder: "New and sealed product..." %>
  </div>

  <div class="flex flex-col mb-2">
    <%= f.label :price %>
    <%= f.number_field :price, class: "w-full md:w-1/2 rounded", placeholder: "$100" %>
  </div>

  <div class="flex flex-col mb-3">
    <%= f.label :photo %>
    <%= f.file_field :photo, class: "bg-blue-200 p-2 rounded w-full md:w-1/2 rounded" %>
  </div>

  <%= f.submit class: "bg-blue-500 p-2 rounded text-white cursor-pointer" %>
<% end %>

app/views/products/_product.html.erb
<div class="product bg-white rounded-lg shadow-xl dark:bg-gray-800 dark:border-gray-700 transition hover:scale-105">
  <%= link_to product_path(product.id), 'data-turbo-frame': '_top' do %>
    <%= image_tag product.photo, class: "p-8 rounded-t-lg" if product.photo.attached? %>
  <% end %>
  <div class="product-details px-5 pb-5">
    <%= link_to product_path(product.id), 'data-turbo-frame': '_top' do %>
      <h5 class="title text-xl font-semibold tracking-tight text-gray-900 dark:text-white"><%= product.title %></h5>
    <% end %>

    <div class="flex justify-between items-center">
      <span class="text-2xl font-bold text-gray-900 dark:text-white">$<%= product.price %></span>
      <%= link_to "See more", product_path(product.id), 'data-turbo-frame': '_top', class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h2 class="text-3xl my-4"><%= t('.title') %></h2>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<%= turbo_frame_tag "home" do %>
  <h1 class="text-4xl my-4"><%= t('.title') %></h1>

  <div class="flex flex-col lg:flex-row mb-4">
    <%= link_to t('.all') ,products_path, class: "mr-2 underline" %>
    <%= render partial: "category", collection: @categories %>
  </div>

  <div class="flex mb-4">
    <%= form_with url: products_path, method: :get do |f| %>
      <%= f.text_field :query_text, placeholder: t('.query_text'), onChange: "this.form.requestSubmit()", value: params[:query_text] %>
      <%= f.number_field :min_price, placeholder: t('.min_price'), onChange: "this.form.requestSubmit()", value: params[:min_price] %>
      <%= f.number_field :max_price, placeholder: t('.max_price'), onChange: "this.form.requestSubmit()", value: params[:max_price] %>
      <%= f.select :order_by, options_for_select(Product::ORDER_BY.keys.map { |order| [t(".#{order}"), order]}, params[:order_by]), {}, { onChange: "this.form.requestSubmit()" } %>
    <% end %>
  </div>

  <%= turbo_frame_tag :products do %>
    <%= turbo_frame_tag "products-#{@pagy.page}" do %>
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-4">
        <%= render partial: "product", collection: @products %>
      </div>
      <%= turbo_frame_tag "products-#{@pagy.next}", src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next %>
    <% end %>
  <% end %>
<% end %>

app/views/products/new.html.erb
<h2 class="text-3xl my-4"><%= t('.title') %></h2>

<%= render "form", product: @product %>

app/views/products/show.html.erb
<h1 class="text-4xl my-4">Product:</h1>

<%= image_tag @product.photo, width: "500px", height: "500px", class: "rounded mb-2" if @product.photo.attached? %>
<div class="product-details">
  <h3 class="title text-3xl font-bold"><%= @product.title %></h3>
  <p class="text-xl font-bold">Price: <span class="price font-normal">$<%= @product.price %></span></p>
  <p class="text-xl font-bold">Description: <span class="description font-normal"><%= @product.description %></span></p>
  <p class="text-xl font-bold">Author: <span class="description font-normal"><%= @product.user.username %></span></p>
</div>
<div class="flex mt-4">
  <%= link_to t('.edit'), edit_product_path(@product), class: "mr-2 inline-block px-6 py-2.5 bg-purple-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-purple-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" if @product.owner? %>
  <%= link_to t('.delete'), product_path(@product), data: { turbo_method: :delete, turbo_confirm: t('common.confirm') }, class: "mr-2 inline-block px-6 py-2.5 bg-rose-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-rose-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out" if @product.owner? %>
  <%= link_to t('.view_more', username: @product.user.username) , user_path(@product.user.username), class: "mr-2 inline-block px-6 py-2.5 bg-purple-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-purple-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
  <%= render partial: "favorite", locals: {product: @product} %>
</div>